# Generated by Django 5.1 on 2024-08-26 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vision', models.TextField(blank=True, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('service_1_name', models.CharField(blank=True, max_length=255, null=True)),
                ('service_1', models.TextField(blank=True, null=True)),
                ('service_2_name', models.CharField(blank=True, max_length=255, null=True)),
                ('service_2', models.TextField(blank=True, null=True)),
                ('service_3_name', models.CharField(blank=True, max_length=255, null=True)),
                ('service_3', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FollowUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GetInTouch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GetQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email_address', models.EmailField(max_length=254)),
                ('service_of_inquiry', models.CharField(choices=[('Software Engineering', 'Software Engineering'), ('SCRUM Framework', 'SCRUM Framework'), ('Website Design & Development', 'Website Design & Development'), ('Mobile Applications Development', 'Mobile Applications Development'), ('Mobile Wallet Development', 'Mobile Wallet Development'), ('ICT Consultancy', 'ICT Consultancy'), ('Payments Integration', 'Payments Integration'), ('Cloud Applications', 'Cloud Applications'), ('Software Support', 'Software Support'), ('Business Process Re-engineering', 'Business Process Re-engineering')], max_length=150)),
                ('further_information', models.TextField(blank=True, null=True)),
                ('date_of_inquiry', models.DateTimeField(auto_now_add=True, null=True)),
                ('assuarance', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='stayUpdated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='WhatWeOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_1_name', models.CharField(blank=True, max_length=255, null=True)),
                ('service_1', models.TextField(blank=True, null=True)),
                ('service_2_name', models.CharField(blank=True, max_length=255, null=True)),
                ('service_2', models.TextField(blank=True, null=True)),
                ('service_3_name', models.CharField(blank=True, max_length=255, null=True)),
                ('service_3', models.TextField(blank=True, null=True)),
                ('service_4_name', models.CharField(blank=True, max_length=255, null=True)),
                ('service_4', models.TextField(blank=True, null=True)),
                ('service_5_name', models.CharField(blank=True, max_length=255, null=True)),
                ('service_5', models.TextField(blank=True, null=True)),
                ('service_6_name', models.CharField(blank=True, max_length=255, null=True)),
                ('service_6', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
