# Generated by Django 5.1 on 2024-08-26 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lp', '0002_about_contactrequest_followus_getintouch_getquote_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetQuoteAssuarance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assuarance', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='getquote',
            name='assuarance',
        ),
    ]
